fix: Fix typeError: mime.getType is not a function
Downgrade @quasar/extras, @quasar/app, quasar, and electron.
I then found out th problem was with the mime package, I compared
node_modules/mime and mime@2.4.5 zip and replaced the missing files.